<a href="https://colab.research.google.com/github/wangjuan001/sandbox2019/blob/master/Copy_of_1_Colab%2C_Python%2C_and_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# __1: Colaboratory, Python, and TensorFlow__

## Learning Objectives

In this notebook, we'll review...
- use of Jupyter Notebooks in Google Colaboratory for interactive Python sessions
- loading TensorFlow modules and basic manipulation of tensors

Today, we'll be building networks in Jupyter Notebooks running on Google Colab. For those of you who are familiar with Jupyter, this will work much the same way it would if you were using Jupyter Notebook or JupyterLab via Anaconda on your own machine. For those of you who aren't, we'll quickly run through Colab and Jupyter functionality.

## __What is Google Colaboratory?__

Google Research launched [__Colaboratory__](https://colab.research.google.com/notebooks/welcome.ipynb), or __Colab__ for short, to provide free access to computing resources, including graphics processing units (GPUs), for educational purposes. Your notebook is running on a virtual machine (VM) on Google's hardware, dedicated to you for a short while (12 hours of continuous runtime).

Some key things to remember:
- Your notebook is in __playground__ (read-only) mode. To write to and save it, you should save a copy to your own Google Drive and work in that notebook instead. Alternatively, you can save a copy to GitHub.
  - `File > Save a copy in Drive`
  - `File > Save a copy in GitHub`
- Your notebook session is connected to your VM. If you leave your notebook open but idle for a while, it will __disconnect__ from the VM, but your data and models will be saved until the VM __shuts down__.
- Eventually, your VM will __shut down__. Any data you had loaded or models built will disappear. There are ways to [save TensorFlow objects to your Google Drive](https://colab.research.google.com/github/tensorflow/models/blob/master/samples/core/tutorials/keras/save_and_restore_models.ipynb), if you are interested.
- If you like, you can open a tensor processing unit (TPU) or graphics processing unit (GPU) accelerated session in `Runtime > Change runtime type`. These options -- especially GPU acceleration -- greatly speed tensor operations including model training. These resources are not guaranteed, though, as they are limited.
  - If you change your runtime type, your VM restarts, meaning all of your data, modules, and models disappear!

## __What is a Jupyter Notebook?__

- Interactive environment for melding executable Python code and text to create a reader-friendly notebook

- Composed of __cells__
  - __Markdown (text) cells__ contain descriptive text (HTML, Markdown, $\LaTeX$) and images
  - __Code cells__ execute instructions in a compatible language and return output
    - Code cells are aware of output of other code cells (__session__)

### Working with code cells

A cell contains interactive code or text. You can add a new code cell by clicking `+ Code` in the top left, and similarly, a new markdown cell by clicking `+ Text`. Let's use a code cell and add two numbers together and assign them into a variable:

In [ ]:
### Two ways to run this cell: the 'Play' button, and Command/Control+Enter


Let's add another code cell to create another variable, and add it to the variable created in the last cell:

<br>
<br>

The last statement producing output in a cell is the only output that will be printed, unless you use the `print()` function:

In [ ]:
print("Here's output.")
print("Here's some more output.")
print("\n\n\nHere's some output after 3 newlines.")

Here's output.
Here's some more output.



Here's some output after 3 newlines.


## __Load and Explore Tensorflow__

Let's load the Python `tensorflow` module. We're careful to load TensorFlow 2.x instead of TensorFlow 1.x below, as the latter is still the default on Google Colab. (Soon, 2.x will be the default.)

In [ ]:
# Until 2.x is the default in Colab, stipulates that we want to load the latest version of TensorFlow 2.0, not 1.x.
%tensorflow_version 2.x
import tensorflow as tf

# Print TF version.
print(tf.__version__)

# Need numpy for a few small things.
from numpy import where, amax

2.2.0


With TensorFlow loaded, we'll get a feel for how tensors are represented and manipulated. Soon, this work will be abstracted away by the Keras API. 

### Warm-up with constant tensors

You can create constant tensors in TensorFlow using list notation.



In [ ]:
# 1D tensor (vector)
t1 = tf.constant(value = [2, 2])
print(t1)   # If we print the tensor object, we see values, shape (dimension), and data type (int32)
print('\nt1 = {}\n'.format(t1))

tf.Tensor([2 2], shape=(2,), dtype=int32)

t1 = [2 2]



In [ ]:
# 2D tensor (matrix), dims (2,2)
t2 = tf.constant(value = [[0, 1], [2, 3]])
print('t2 = {}\n'.format(t2))

t2 = [[0 1]
 [2 3]]



In [ ]:
# 3D tensor, dims (2,2,2)
t3 = tf.constant(value = [[[0, 1], [2, 3]], [[10, 20], [30, 40]]])
print('t3 = {}'.format(t3))

t3 = [[[ 0  1]
  [ 2  3]]

 [[10 20]
  [30 40]]]


Basic addition and subtraction operations work essentially the way you expect:

In [ ]:
# Using the add() method:
print('Addition:\n tf.add(t3, t3) =\n {}\n'.format(tf.add(t3, t3)))

# Using the overloaded `+` operator:
print('t3 + t3 =\n {}\n'.format(t3 + t3))

# Using the subtract() method:
print('Subtraction:\n tf.subtract(t3, t3) =\n {}\n'.format(tf.subtract(t3, t3)))

# Using the overloaded `-` operator:
print('t3 - t3 =\n {}'.format(t3 - t3))

Addition:
 tf.add(t3, t3) =
 [[[ 0  2]
  [ 4  6]]

 [[20 40]
  [60 80]]]

t3 + t3 =
 [[[ 0  2]
  [ 4  6]]

 [[20 40]
  [60 80]]]

Subtraction:
 tf.subtract(t3, t3) =
 [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]

t3 - t3 =
 [[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


Element-wise tensor multiplication and division:

In [ ]:
print('Element-wise multiplication:\n tf.multiply(t3, t3) =\n {}\n'.format(tf.multiply(t3, t3)))

print('Element-wise division:\n tf.divide(t3, t3) =\n {}\n'.format(tf.divide(t3, t3)))  # Notice this returns floating point values.

# Try the operator overloads * and / to verify:
t3 * t3 
t3/ t3

Element-wise multiplication:
 tf.multiply(t3, t3) =
 [[[   0    1]
  [   4    9]]

 [[ 100  400]
  [ 900 1600]]]

Element-wise division:
 tf.divide(t3, t3) =
 [[[nan  1.]
  [ 1.  1.]]

 [[ 1.  1.]
  [ 1.  1.]]]



<tf.Tensor: shape=(2, 2, 2), dtype=float64, numpy=
array([[[nan,  1.],
        [ 1.,  1.]],

       [[ 1.,  1.],
        [ 1.,  1.]]])>

Matrix multiplication and exponentiation. Note that matrix multiplication is actually "batch multiplication" if tensor rank >2.

In [ ]:
print('Matrix multiplication:\n tf.matmul(t3, t3) =\n {}\n'.format(tf.matmul(t3, t3)))

print('Exponentiation:\n tf.pow(t3, 2) =\n {}\n'.format(tf.pow(t3, 2)))

Matrix multiplication:
 tf.matmul(t3, t3) =
 [[[   2    3]
  [   6   11]]

 [[ 700 1000]
  [1500 2200]]]

Exponentiation:
 tf.pow(t3, 2) =
 [[[   0    1]
  [   4    9]]

 [[ 100  400]
  [ 900 1600]]]



Applying a function to a tensor (there are [lots of others](https://www.tensorflow.org/api_docs/python/tf/math)):

In [ ]:
# Sigmoid operation accepts floating point and complex values:
t4 = tf.constant(value = [[1., 2.], [-1., -2.]])
print('Sigmoid:\n tf.pow(t3, 2) =\n {}\n'.format(tf.sigmoid(t4)))

Sigmoid:
 tf.pow(t3, 2) =
 [[0.7310586  0.880797  ]
 [0.26894143 0.11920292]]



### Note: constant vs variable tensors

The difference between a `tf.constant` and a `tf.Variable` tensor is irrelevant for this workshop, but is important if you go on to write advanced or custom functionality in TensorFlow. Because we'll be using a lot of functions that abstract the particulars away, the distinction only warrants a quick mention here.

In short:
- __Changes in value__: `tf.Variable` tensors are subject to any changes made by optimization of a neural network. That is, any `tf.Variable` in a neural network will change as a result of backpropagation updates. The value of `tf.Constant` does not change -- a new `tf.constant` must be created in its place.

- __Persistence__: `tf.Variable` can be saved to disk. This is useful, for example, to save neural network weights to a portable model file. `tf.Constant` is initialized anew in every session.

- __Memory requirements__: `tf.Constant` is stored directly in the computational graph definition, and can take up a lot of room in memory if the constant is of significant size. In contrast, `tf.Variable` is a set of instructions to obtain a tensor value, and is hence pretty memory lightweight.


In [ ]:
# Some examples:
v1 = tf.Variable([2, 2]) 
v2 = tf.Variable([[0, 1], [2, 3]]) 
v3 = tf.Variable(tf.zeros([784,10]))

print('v1 = {}\n'.format(v1))
print('v2 = {}\n'.format(v2))
print('v3 = {}'.format(v3))

v1 = <tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([2, 2], dtype=int32)>

v2 = <tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[0, 1],
       [2, 3]], dtype=int32)>

v3 = <tf.Variable 'Variable:0' shape=(784, 10) dtype=float32, numpy=
array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)>


### __Exercise__ (~5-10 min)

__1a: Manipulating tensors of differing size__

Add together `v1` and `v2`. Multiply (element-wise) `v1` and `v2`. How are the results computed?

In [ ]:
v1 + v2 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [ ]:
v1 * v2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 2],
       [4, 6]], dtype=int32)>

__1b: Reshaping and flattening tensors__

Take a look at the documentation for [`tf.reshape()`](https://www.tensorflow.org/api_docs/python/tf/reshape). Reshape `v3` into a $28 \times 28 \times 10$ 3D tensor and assign the result into `v4`. Then, reshape `v4` into a 1D tensor.

In [ ]:
v4 = tf.reshape(v3, shape=(28,28,10))

In [ ]:
v4 = tf.reshape(v4,shape = 28*28*10)
print(v4)

tf.Tensor([0. 0. 0. ... 0. 0. 0.], shape=(7840,), dtype=float32)


__1c: Emulate the activation of a layer for one training example__

1. Use `tf.matmul()` to compute the product of `input_dat` and `weights` (should be of shape `(1, 5)`).
2. Use `tf.keras.activation.softmax()` to find the most activated neuron for `input_dat`. For a 1D tensor of size $(J,)$, the softmax function computes a probability distribution:
\begin{equation*}
\text{softmax}(x_{i}) = \frac{\exp(x_{i})}{\sum_{j=1}^{J}\exp(x_{j})}
\end{equation*}

In [ ]:
# An observations with 10 random features between -5 and 5.
input_dat =  tf.random.uniform(minval = -5, maxval = 5, shape = (1, 10))
print(input_dat)
# Weight matrix for a hidden layer of 5 nodes. 
# Each weight is connected to one of the 10 inputs, and one of the 5 hidden neurons.
weights = tf.random.uniform(minval = -1, maxval = 1, shape = (10, 5))
print(weights)
# 1. multiply input_dat and weights:
product = tf.matmul(input_dat, weights)

# 2. Use the softmax activation on product:
activation = tf.keras.activations.softmax(product)
print(activation)

# Get max value and its index.
max_val = amax(activation)
max_index = where(activation == amax(max_val))[1][0]
print("\nMax value: {}\n".format(max_val) + \
      "Max value index (0-4): {}\n".format(max_index))

tf.Tensor(
[[-2.0839047   2.5628734  -3.8922763  -1.0329175   2.6773825  -1.4718235
  -3.7886274   1.8291769  -0.25531197 -4.1612577 ]], shape=(1, 10), dtype=float32)
tf.Tensor(
[[-0.9391401  -0.9435127  -0.3741567   0.3157351   0.58059096]
 [ 0.41424203  0.68347573  0.72885585  0.2497077   0.9636977 ]
 [ 0.6632545   0.48962402  0.07781911  0.7634678   0.03951311]
 [ 0.37000275  0.741487   -0.47672248  0.5983021  -0.8072009 ]
 [ 0.608032   -0.03554559  0.7871008   0.03919029  0.1940651 ]
 [-0.28318954 -0.23832488  0.01291895 -0.48528075  0.7637727 ]
 [-0.6235175  -0.34217548 -0.9275589   0.15054035  0.5206175 ]
 [-0.7343688  -0.19141221 -0.2939663   0.5617299   0.38440967]
 [-0.9929693  -0.30884576 -0.83459234  0.5526452   0.82713485]
 [ 0.8124752   0.0850625   0.09059381  0.72587824  0.5749178 ]], shape=(10, 5), dtype=float32)
tf.Tensor([[4.3056882e-04 3.1236294e-03 9.9640971e-01 1.7875844e-06 3.4341003e-05]], shape=(1, 5), dtype=float32)

Max value: 0.9964097142219543
Max value index

__1d (optional): Download or save a copy of this notebook to your Google Drive to preserve your changes.__

## __Next__: using TensorFlow to build networks.